version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=rw_sfm
     - POSTGRES_USER=rw_sfm
     - POSTGRES_PASSWORD=rw_sfm
     - MAX_CONNECTIONS=300
   networks:
     - compose_postgres

networks:
  compose_postgres:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.68.70.1/24